### ISSUE TITLE
[Feature Request] Firefox support

### ISSUE THREAD

**Issue by GuillaumeAmat** [React-Sight/React-Sight#109]
Is there a plan to support Firefox too?

**Comment by davidcsally** [comment]
Not at this time, perhaps after we fix all the outstanding bugs we can look into porting it to Firefox. It shouldn't be too difficult to port, but I haven't played around with firefox extensions myself

**Comment by davidcsally** [comment]
@GuillaumeAmat Hey 👋! I actually did this! As someone who has recently switched to Firefox, I was curious how feasible this would be. Turns out it's incredibly easy, since Firefox and Chrome use the same browser extension standards. Here is the PR to add Firefox support: https://github.com/React-Sight/React-Sight/pull/178. I will follow up with a documentation update with clear instructions on how to use this in Firefox. Additionally, it is currently pending review on the Firefox addon website.

**Comment by davidcsally** [comment]
Updated docs here: https://github.com/React-Sight/React-Sight/pull/179. I will close this when it's released on the Firefox addon page.

**Comment by davidcsally** [comment]
Live! https://addons.mozilla.org/en-US/firefox/addon/react-sight/ 

I will close this issue now

**Comment by GuillaumeAmat** [comment]
Great thanks @davidcsally ! ❤️

Though, it seems that I have the #134 issue... It does not work on remote or local React websites. Also, the last version of react-sight is 1.2.0 but I only see the 1.1.0 on the Mozilla addon page.

**Comment by davidcsally** [comment]
It’s actually the correct version at Mozilla, but I forgot to bump the version number 😬. Expect a 1.2.1 soon. I’m waiting for the chrome approval before I bump again. 

As for the error, I’ll test some more today. I think there is a major issue with React 16, where React will not be detected until something re-renders

**Comment by davidcsally** [comment]
This has been released!
