### ISSUE TITLE
Chrome Extension link is broken in the documentation

### ISSUE THREAD

**Issue by paoloricciuti** [React-Sight/React-Sight#294]
The link to the chrome extension either in the documentation or in the website does not work (it goes to 404)

**Comment by davidcsally** [comment]
I no longer maintain this. It was removed because I did not update the permissions

**Comment by paoloricciuti** [comment]
Oh that's a shame. Well thanks anyway.

**Comment by slecholineas** [comment]
I unfortunately have no ready to use yarn environment for doing the build myself. Would it be possible to have the required files to do the 'Unpack loaded' ?

**Comment by 503Dev** [comment]
@davidcsally I have free time and use this extension alot.  Great work.  Would you be willing to allow me to update it, fix some minor things, fix perms and republish it for others? I would of course provide proper credits and follow your licensing terms.  I want to ask permission rather than just fork it like a jerk

**Comment by davidcsally** [comment]
@503Dev go for it!

**Comment by zachdixon** [comment]
@503Dev Curious if you've started on updating this? Would love to give this a try, can't really find anything else like it.
